[package]
name = "roguelike"
version = "0.1.0"
edition = "2024"

[dependencies]
#tcod = { version = "0.15.0", features ["serialization"] }
tcod = { git= "https://github.com/tomassedovic/tcod-rs.git"}
rand = "0.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"